CREATE TABLE IF NOT EXISTS app_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_messages (key, value)
VALUES ('HELLO_WORLD', 'Hola Mundo desde SQLite')
ON CONFLICT(key) DO NOTHING;
